apiVersion: batch/v1
kind: Job
metadata:
  name: space-launch-job
spec:
  template:
    spec:
      containers:
      - name: space-launch-container
        image: ${{ vars.DOCKER_USERNAME}}:latest
        command: ["dotnet", "SpaceLaunch.dll"]
      
  backoffLimit: 1