apiVersion: batch/v1
kind: Job
metadata:
  name: space-launch-job
  namespace: space-launch-namespace
spec:
  template:
    metadata:
      labels:
        app: space-launch
    spec:
      containers:
        - name: space-launch-container
          image: imdow/devopsrepo:latest-${TAG}
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          command: ["dotnet"]
          args: ["SpaceLaunch.dll"]
      restartPolicy: OnFailure