name: CD Pipeline

on:
    workflow_run:
      workflows: ["CI pipeline"]
      types:
        - completed
    workflow_dispatch:
      inputs:
        target:
          description: "Select deployment target: (aws/minikube)"
          required: true
          default: "minikube"


jobs:
  deploy-to-minikube:
    runs-on: ubuntu-latest
    if: ${{github.event.inputs.target}} == minikube

    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Check minikube status
        run: 
          minikube status

      - name: Deploy to Kubernetes
        run: |  
          kubectl apply -f Kubernetes/Deployment.yaml
      
      - name: Wait for deployment to be ready
        continue-on-error: true
        run: |
         kubectl wait --for=condition=ready pod -l app=space-launch --timeout=60s

      - name: See logs
        run: |
          kubectl get pods -A | grep "space-launch-deployment" | awk '{print $2}' | xargs -I {} kubectl logs {}

      - name: See pods
        if: always()
        run: |
          kubectl get pods -A

      - name: Stop minikube
        if: always()
        run: |
           minikube stop    